services:
  drose-web:
    build: .
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "bun", "-e", "fetch('http://localhost:3000/api/health').then(r => r.ok ? process.exit(0) : process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - coolify
    environment:
      - PORT=3000
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_MESSAGING_SID=${TWILIO_MESSAGING_SID}
      - TWILIO_TO_PHONE=${TWILIO_TO_PHONE}
      - NTFY_SERVER=${NTFY_SERVER}
      - NTFY_TOPIC=${NTFY_TOPIC}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: unless-stopped
    volumes:
      # Persist thread data only
      - threads-data:/app/data

networks:
  coolify:
    name: coolify
    external: true

volumes:
  threads-data:
